pipeline {
    agent { label('master && slave1') }
    stages {
        stage('Build') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh '''
                        #!/bin/bash 
                        pwd 
                        ls
                        echo "This is a BUILD stage"
                        sleep 5
                        exit 1
                    ''' 
                }     
            }
        }

        stage('DEPLOY') {
            steps {
                echo "This is a DEPLOY stage"
                sh 'sleep 5'
            }
        }
    }
}