pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    #!/bin/bash 
                    pwd 
                    ls
                    echo "This is a BUILD stage"
                    sleep 5
                    exit 1
                '''  
            }
        }

        stage('DEPLOY') {
            steps {
                echo "This is a DEPLOY stage"
                sh 'sleep 5'
            }
        }
    }
}